---
- hosts: localhost
  gather_facts: no
  tasks:
    - sw_system_list:
        url: https://spacewalk.example.com/rpc/api
        user: sw_admin
        password: My super secret password!
      register: systems

    - debug: msg="{{item}}"
      loop: "{{systems.system_list}}"
